name: Build and Test C Project

on:
  push:
    branches:
      - for-java

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build-essential
        run: sudo apt-get install build-essential -y

      - name: Compile C code
        run: make

      - name: Set execute permission for script.sh
        run: chmod +x ./test/script.sh

      - name: Run unit tests
        run: |
          ./test_prime
          ./test/script.sh